---

- name: Configure nginx
  block:

    - name: selinux disable permanently
      selinux:
        policy: targeted
        state: permissive
      when: virt.stdout != "lxc"

    - name: set in permissive without reboot
      command: setenforce 0
      ignore_errors: true
      changed_when: false
      when: virt.stdout != "lxc"

    - name: update nginx config
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: nginx
      notify:
        - reload nginx

    - name: update nginx statics
      copy:
        src: "files/"
        dest: "{{ root_dir }}"
        owner: nginx
      notify:
        - reload nginx
