---

- name: Prepare step for nginx
  block:
    - name: Mount up device
      parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
      when: virt.stdout != "lxc"

    - name: create filesystem
      filesystem:
        fstype: xfs
        dev: /dev/sdb1
      when: virt.stdout != "lxc"

    - name: Mount up device by label
      mount:
        path: /data
        src: /dev/sdb1
        fstype: xfs
        state: mounted
      when: virt.stdout != "lxc"

    - name: create directory for nginx files
      file:
        path: "{{ root_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root
