- hosts: appservers
  vars:
    root_dir: "/data/nginx/html"

  tasks:
    - name: Find out if it is baremetal or vm
      command: "systemd-detect-virt"
      register: virt
      ignore_errors: true

    - name: selinux disable permanently
      selinux:
        policy: targeted
        state: permissive
      when: virt.stdout != "lxc"

    - name: set in permissive without reboot
      command: setenforce 0
      ignore_errors: true
      changed_when: false
      when: virt.stdout != "lxc"

    - name: Mount up device
      parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
      become: yes
      when: virt.stdout != "lxc"


    - name: create filesystem
      filesystem:
        fstype: xfs
        dev: /dev/sdb1
      become: yes
      when: virt.stdout != "lxc"

    - name: Mount up device by label
      mount:
        path: /data
        src: /dev/sdb1
        fstype: xfs
        state: mounted
      become: yes
      when: virt.stdout != "lxc"

    - name: create directory for nginx files
      file:
        path: "{{ root_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root
      become: yes


    - name: Install nginx packages
      block:
        - name: Install EPEL repo
          yum:
            name: epel-release
            state: present

        - name: install nginx server
          yum:
            name: nginx
            state: present
            update_cache: yes

    - name: update nginx config
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: nginx
      notify:
        - reload nginx
      become: yes

    - name: update nginx statics
      copy:
        src: "files/"
        dest: "{{ root_dir }}"
        owner: nginx
      notify:
        - reload nginx
      become: yes

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
        daemon_reload: yes
        enabled: yes
      become: yes
